config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get '/pcj' => redirect("https://docs.google.com/a/iiitd.ac.in/forms/d/1fCqlJgchtazO-ZPOM1TniR_k4OfSOTvABJ584xrQJo4/viewform")
  get '/blog' => redirect("/blog/")
  get '/comedynight' => redirect("/comedynight/")
  get '/archive/2014' => redirect("/archive/2014/")
  get '/hackiiitd' => redirect("/hackiiitd/")

  scope 'm' do
    resources :organizers, only: [:index]
    resources :static_pages, only: [:index,:show]
    resources :sponsors, only: [:index]
    resources :events, only: [:index,:show]
    get '/register/:id(/:team_code)' => "registrations#create"
    get '/register/:id(/team/:team_name)' => "registrations#create"
    get '/check_registration/:id' => "registrations#check"
    get '/profile' => 'participants#profile'
    post '/profile/update' => "participants#update"
    get "/" => 'landings#mhome'
    get '/login'  => "sessions#create_api"
    post '/register_gcm' => "sessions#create_gcm"
    get '/schedule' => "landings#schedule"
  end

  get '/register/:short_code' => "registrations#new_event",as: :register_event
  post '/register/:id' => "registrations#form_create",as: :form_create
  get '/register' => "registrations#new"

  get '/coming_soon' => 'landings#coming_soon'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin/:provider(/:type)' => 'sessions#new', :as => :signin
  delete '/signout' => 'sessions#destroy', :as => :logout
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'

  get '/(:type/:value)' => 'landings#home', as: :ide
  root 'landings#home'
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  layout :resolve_layout
  before_filter :check_mobile, only: [:home]
  def index
  end
  def home
    @type = params[:type]
    @value = params[:value]
  end
  def mhome
    @pages = StaticPage.all
  end
  def coming_soon
  end

  def schedule
    @schedule = '<img src="http://esya.iiitd.edu.in/img/Day1.png" class="schedule"> <img src="http://esya.iiitd.edu.in/img/Day2.png" class="schedule">'
    render json: {combined: @schedule,name: "Schedule"}
  end

  private

  def resolve_layout
    case action_name
    when "index", "mhone"
      "application"
    when "home"
      "ide"
    when "coming_soon"
      "cs"
    else
      "application"
    end
  end
end

app/views/landings/coming_soon.html.erb
<div class="container padding">
  <div class="row row15">
    <div class="row row15">
      <center>
      <%= image_tag "Logo.png", :class => "image"%>
      </center>
    </div>
    <br><br>
    <h1 style="text-align:center;font-weight:300" class="coming"> COMING SOON </h1>
    <div class="row row15">
      <div class="col-md-4 col-md-push-4 col-sm-4 col-sm-push-4 col-xs-8 col-xs-push-2" style="text-align:center;font-size:20px;font-weight:100">
        We are currently working on an awesome new site.
      </div>
    </div>
    <!-- <br> -->
    <div class="row row15">
      <div class="col-md-4 col-md-push-4" style="text-align:center;font-size:32px; font-weight:500">
        Stay Tuned !
      </div>
    </div>
    <br><br><br>

    <div class="row">
      <div class="col-md-4 col-md-push-4 col-sm-6 col-sm-push-3 col-xs-8 col-xs-push-2" style="text-align:center;font-size:32px; font-weight:500">
        <hr class="col-xs-1" style="border-top-color: black;" />
        <p class="col-xs-8" style="margin-top:-3px">Follow us</p>
        <hr class="col-xs-1" style="border-top-color: black;">
      </div>
    </div>
    <br />
    <br />

    <div class="row row15">
      <div id="pro" class="col-md-1 col-md-push-4 col-sm-3 col-xs-3">
        <a href="https://www.facebook.com/EsyaIIITD" target="_blank"><%= image_tag "Fb.png", :class => "link"%></a>
      </div>
      <div id="pro" class="col-md-1 col-md-push-4 col-sm-3 col-xs-3">
        <a href="http://esya.iiitd.edu.in/blog/" target="_blank"><%= image_tag "Blog.png", :class => "link"%></a>
      </div>
      <div id="pro"class="col-md-1 col-md-push-4 col-sm-3 col-xs-3">
        <a href="https://instagram.com/esya_iiitd" target="_blank"><%= image_tag "Insta.png", :class => "link"%></a>
      </div>
      <div id="pro" class="col-md-1 col-md-push-4 col-sm-3 col-xs-3">
        <a href="https://twitter.com/EsyaIIITD" target="_blank"><%= image_tag "Twitter.png", :class => "link"%></a>
      </div>
    </div>
  </div>
</div>

app/views/landings/home.html.erb
<div id="loading">
  <div id="loading-center">
    <div id="loading-center-absolute">
      <img id="loadinglogo" style="float: left;width:400px" src="/img/e151.png"/>
      <div class="object" id="object_one"></div>
      <div class="object" id="object_two"></div>
      <div class="object" id="object_three"></div>
    </div>
  </div>
</div>


<div class="top_wrapper" id="top_part" style="height: 75%">
  <div class="fixed">
    <div class="large-12 columns dark_black" style="text-align: center">
      <img id="logo" style="float: right;" src="/img/HeaderRight.png"/>
      <img id="logo" style="float: left;height: 55px" src="/img/e153.png"/>
      <img id="logo" class=""  src="/img/HeaderLeft.png"/>
    </div>
  </div>

  <div class="inner_ide" style="padding-top: 60px;background: white;height: 100%">
    <div id="navigation" class="small-3 columns nomarpad" style="height: 100%">
      <div class="small-1 columns nomarpad" id="ext_links">
        <div class="side_link first_link tip-right has-tip" data-tooltip aria-haspopup="true" class="" title="IIIT Delhi Website">
          <a href="http://iiitd.ac.in"><i class="fa fa-building"></i></a>
        </div>
        <div class="side_link mid_link tip-right has-tip" data-tooltip aria-haspopup="true" class="" title="Esya Blog">
          <a href="http://esya.iiitd.edu.in/blog/"><i class="fa fa-pencil"></i></a>
        </div>
        <div class="side_link mid_link tip-right has-tip" data-tooltip aria-haspopup="true" class="" title="Esya@facebook">
          <a href="https://www.facebook.com/EsyaIIITD"><i class="fa fa-facebook"></i></a>
        </div>
        <div class="side_link mid_link tip-right has-tip" data-tooltip aria-haspopup="true" class="" title="Esya@instagram">
          <a href="https://instagram.com/esya_iiitd"><i class="fa fa-instagram"></i></a>
        </div>
        <div class="side_link mid_link tip-right has-tip" data-tooltip aria-haspopup="true" class="" title="Esya@twitter">
          <a href="https://twitter.com/EsyaIIITD"><i class="fa fa-twitter"></i></a>
        </div>
        <div class="side_link last_link tip-right has-tip" data-tooltip aria-haspopup="true" class="" title="Github Repo">
          <a href="https://github.com/rush-skills/esya2015"><i class="fa fa-github"></i></a>
        </div>
      </div>
      <div class="small-11  columns nomarpad" style="overflow: auto;height: 100%">
        <ol class="tree" style="padding: 20px 0px">
          <li>
            <label for="folder1"><s class="fi-folder"></s> ESYA</label> <input type="checkbox" checked disabled id="folder1" />
            <ol>
              <li>
                <label for="subfolder1"><s class="fi-folder"></s> Events</label> <input type="checkbox" id="subfolder1" />
                <ol>
                  <li>
                    <label for="subsubfolder3"><s class="fi-folder"></s> Flagship</label> <input type="checkbox" id="subsubfolder3" />
                    <ol id="Flagship_events">
                    </ol>
                  </li>
                  <li>
                    <label for="subsubfolder7"><s class="fi-folder"></s> Techathlon</label> <input type="checkbox" id="subsubfolder7" />
                    <ol id="Techathlon_events">
                    </ol>
                  </li>
                  <li>
                    <label for="subsubfolder1"><s class="fi-folder"></s> CSE</label> <input type="checkbox" id="subsubfolder1" />
                    <ol id="CSE_events">
                    </ol>
                  </li>
                  <li>
                    <label for="subsubfolder2"><s class="fi-folder"></s> ECE</label> <input type="checkbox" id="subsubfolder2" />
                    <ol id="ECE_events">
                    </ol>
                  </li>
                  <li>
                    <label for="subsubfolder4"><s class="fi-folder"></s> School</label> <input type="checkbox" id="subsubfolder4" />
                    <ol id="School_events">
                    </ol>
                  </li>
                  <li>
                    <label for="subsubfolder5"><s class="fi-folder"></s> Workshop</label> <input type="checkbox" id="subsubfolder5" />
                    <ol id="Workshop_events">
                    </ol>
                  </li>
                  <li>
                    <label for="subsubfolder6"><s class="fi-folder"></s> Non tech Events</label> <input type="checkbox" id="subsubfolder6" />
                    <ol id="Non_tech_events">
                    </ol>
                  </li>
                </ol>
              </li>
            </ol>
          </li>
        </ol>
      </div>
    </div>

    <div class="small-9 columns dark_black" id="file_tabs" style="min-height: 7%;" id="file_explorer">
      <ul class="tabs dark_black" data-tab>
        <li class="tab-title active light_black text_white" id="tabs_esya"><a class="border-left-blue" href="#" id="first_tab">Esya.html</a><a class="text_blue" href="<%= ide_url %>" onclick="resetPage()">x</a></li>

        <li id="fallback" class="border-left-blue tab-title right light_black text_white" style="width: 200px;margin:0;margin-left: 15px;" onclick="window.location = '/m'">
          <a href="/m" id="fallback-link" class="light_black text_white">Mobile/Easy Website</a>
        </li>
        <% if participant_signed_in? %>
        <li id="login" data-logged-in="1" class="border-left-blue tab-title right light_black text_white" style="width: 150px;margin:0;margin-left: 15px;">
        <a data-dropdown="drop2" aria-controls="drop1" aria-expanded="false" class="light_black text_white"><%= current_participant.name %></a>
        <ul id="drop2" class="light_black text_white f-dropdown" data-dropdown-content aria-hidden="true" tabindex="-1">
          <li><a href="#" id="profile" class="text_white hover_black">Profile</a></li>
          <li><a href="/signout" class="text_white hover_black">Log out</a></li>
        </ul>
        </li>
        <% else %>
        <li id="login" data-logged-in="0" class="border-left-blue tab-title right light_black text_white" style="width: 100px;margin:0;margin-left: 15px;">
        <a data-dropdown="drop1" aria-controls="drop1" aria-expanded="false" class="light_black text_white">Login</a>
        <ul id="drop1" class="light_black text_white f-dropdown" data-dropdown-content aria-hidden="true" tabindex="-1">
          <li><a href="/signin/google_oauth2" class="text_white hover_black">Google</a></li>
          <li><a href="/signin/facebook" class="text_white hover_black">Facebook</a></li>
        </ul>
        </li>
        <% end %>
        <li class="border-left-blue tab-title right light_black text_white" style="margin:0">
          <a href="#" data-team-id="" data-team-size="" data-registered="" data-team-event="" data-event-id="" data-event-name="" id="register" class="light_black text_white" style="display: none">Register</a>
        </li>
      </ul>
    </div>

    <div class="small-9 columns" id="editor_area" style="height: 93%; margin:0; padding:0;">
      <div style="height: 100%;" id="editorWrapper" class="nano">
        <div class="nano-content">
          <textarea style="height: 100%;  margin:0; padding: 20px; border: solid 3px black;" class="wysiwyg-color-white" id="wysihtml5-editor" spellcheck="false" wrap="off" autofocus placeholder="<h1>Hey!</h1> <p>We're yet to add content to this page</p>">
            <h1>Welcome to Esya 2015!</h1><h3>Click on a page in the left to get started.</h3><img src="/img/e151.png" height="100">
          </textarea>
        </div>
      </div>

    </div>
  </div>
</div>
<div class="small-12 nomarpad columns dark_black" style="height: 3%">
  <ul class="tabs dark_black" data-tab style="height: 100%;font-size: 13px">
    <li class="console_tab nomarpad active dark_black text_white" id="tabs_esya" style="height: 100%;"><a href="#" id="first_tab">Console</a></li>
  </ul>
</div>

<div class="small-12 columns" id="term_part" style="height: 22%;margin: 0;padding: 0">
  <div id="commandLine" class="panel" style="margin-bottom: 0px">
  </div>
</div>

<script type="text/javascript">
  $(window).load(function() {
   $("#loading").fadeOut(200);
 });
</script>

app/views/landings/index.html.erb
<h1>Landings#index</h1>
<p>Find me in app/views/landings/index.html.erb</p>

app/views/landings/mhome.html.erb
<!-- Header -->
<header id="top" class="header" style="padding-top:53px">
    <div class="text-vertical-center">
        <h1><img src="/img/logo.png" class="logo"></h1><br>
        <h2 style="color:white">The Annual Technical Festival <br>21st August - 22nd August</h3><br>
        <h1 style="color:white; font-weight:100">Going Opensource</h1>
        <br>
        <a href="#event" class="btn btn-dark btn-lg" style="font-size:40px">V</a><!--Replace this with down arrow-->
    </div>
</header>

<section id="event" class="services bg-prime header">
    <div class="container text-vertical-center">
        <div class="row text-center">
            <div class="col-lg-10 col-lg-offset-1">
                <h2 style="color:white">Esya 2015</h2>
                <hr class="small">
                <div class="row">
                    <div class="col-md-4 col-sm-4 col-xs-6 tile">
                        <div class="inner-tile">
                            <%= link_to "Events", events_path %>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-4 col-xs-6 tile">
                        <div class="inner-tile">
                            <%= link_to "Sponsors", sponsors_path %>
                        </div>
                    </div>
                    <% @pages.each do |page| %>
                        <div class="col-md-4 col-sm-4 col-xs-6 tile">
                            <div class="inner-tile">
                                <%= link_to page.to_s, static_page_path(page) %>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- <section id="contact" class="bg-prime header">
    <div class="container text-vertical-center">
        <div class="row text-center">
            <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1">
                <h2 style="color:white">Contact Us</h2>
                <hr class="large" style="; margin-bottom:50px">
                <form>
                    <div class="row">
                        <div class="col-md-6 col-sm-6 col-xs-10 col-xs-push-1 col-sm-push-0">
                            <div class="form-group">
                            <input type="text" class="form-control dark-input text-field" placeholder="Name">
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-10 col-xs-push-1 col-sm-push-0">
                            <div class="form-group">
                            <input type="text" class="form-control dark-input text-field" placeholder="Email">
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-10 col-xs-push-1 col-sm-push-0">
                            <div class="form-group">
                            <input type="text" class="form-control dark-input text-field" placeholder="Phone No.">
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-10 col-xs-push-1 col-sm-push-0">
                            <div class="form-group">
                            <input type="text" class="form-control dark-input text-field" placeholder="Subject">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-10 col-xs-push-1 col-sm-push-0">
                            <div class="form-group">
                            <textarea class="form-control dark-input" placeholder="Message" style="resize:none; height:100px; border-radius:0px"></textarea>
                            </div>
                        </div>
                    </div>
                    <div class="row" style="margin-bottom:50px;">
                        <div class="col-md-12 col-sm-12 col-xs-10 col-xs-push-1 col-sm-push-0">
                            <input type="submit" class="btn btn-lg btn-submit" style="width:100%" placeholder="SUBMIT">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section> -->