config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get '/pcj' => redirect("https://docs.google.com/a/iiitd.ac.in/forms/d/1fCqlJgchtazO-ZPOM1TniR_k4OfSOTvABJ584xrQJo4/viewform")
  get '/blog' => redirect("/blog/")
  get '/comedynight' => redirect("/comedynight/")
  get '/archive/2014' => redirect("/archive/2014/")
  get '/hackiiitd' => redirect("/hackiiitd/")

  scope 'm' do
    resources :organizers, only: [:index]
    resources :static_pages, only: [:index,:show]
    resources :sponsors, only: [:index]
    resources :events, only: [:index,:show]
    get '/register/:id(/:team_code)' => "registrations#create"
    get '/register/:id(/team/:team_name)' => "registrations#create"
    get '/check_registration/:id' => "registrations#check"
    get '/profile' => 'participants#profile'
    post '/profile/update' => "participants#update"
    get "/" => 'landings#mhome'
    get '/login'  => "sessions#create_api"
    post '/register_gcm' => "sessions#create_gcm"
    get '/schedule' => "landings#schedule"
  end

  get '/register/:short_code' => "registrations#new_event",as: :register_event
  post '/register/:id' => "registrations#form_create",as: :form_create
  get '/register' => "registrations#new"

  get '/coming_soon' => 'landings#coming_soon'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin/:provider(/:type)' => 'sessions#new', :as => :signin
  delete '/signout' => 'sessions#destroy', :as => :logout
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'

  get '/(:type/:value)' => 'landings#home', as: :ide
  root 'landings#home'
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id                    :integer          not null, primary key
#  name                  :string
#  rules                 :text
#  judging               :text
#  event_date_time       :datetime
#  team_size             :integer
#  venue                 :string
#  eligibilty            :string
#  registration_deadline :datetime
#  prizes                :text
#  contact               :text
#  photo                 :string
#  created_at            :datetime
#  updated_at            :datetime
#  description           :text
#  short_code            :string
#
# Indexes
#
#  index_events_on_short_code  (short_code) UNIQUE
#

class Event < ActiveRecord::Base
  has_paper_trail

  has_many :event_admins
  has_many :users, through: :event_admins
  has_many :registrations
  has_many :teams, dependent: :destroy
  has_many :participants, through: :teams
  has_many :notifications
  has_and_belongs_to_many :categories

  validates :name, presence: true
  validates :team_size, presence: true
  validates :team_size, numericality: { only_integer: true, :less_than_or_equal_to => 6, :greater_than_or_equal_to => 1 }

  mount_uploader :photo, PhotoUploader
  attr_accessor :photo_cache, :remove_photo
  extend Enumerize

  before_update :generate_short_code

  def to_s
    self.name
  end

  def team_event?
    self.team_size > 1
  end

  def registered?(participant)
    Registration.where(participant: participant, event: self).first.present? or self.participants.where(id: participant.id).first.present?
  end

  def get_team participant
    self.participants.where(id: participant.id).get_team(self)
    self.save!
  end

  def generate_short_code
    self.short_code = self.name.squish.downcase.tr(" ","_").tr(".","_")
  end

  def is_admin user
    self.event_admins.where(user: user).first.present?
  end

  def info
    string = ""
    string += '<div class="image-center"><img height="250px" src="'+self.photo.url+'"></div>' if self.photo.present?
    # string += '<p>Event Name: '+self.name.to_s+'</p>'
    # string +='<p>Category: '+self.category.to_s+'</p>'
    string +='<h2 align="center"><b>Team size limit:</b> '+self.team_size.to_s+' people'
    string +='&nbsp&nbsp|&nbsp&nbsp<b>Eligibility:</b> '+self.eligibilty.to_s if self.eligibilty.present?
    string += '&nbsp&nbsp|&nbsp&nbsp<b>Time:</b> '+self.event_date_time.strftime("%D %r") if self.event_date_time.present?
    string += '<br><b>Registration Deadline:</b> '+self.registration_deadline.strftime("%D %r") if self.registration_deadline.present?
    string += '&nbsp&nbsp|&nbsp&nbsp<b>Venue:</b> '+self.venue.to_s if self.venue.present?
    string += '</h2>'
  end
  def combined
    string = info
    string += "<h1>Description</h1>" + self.description.to_s if self.description.present?
    string += "<h1>Rules</h1>" + self.rules.to_s if self.rules.present?
    string += "<h1>Judging</h1>" + self.judging.to_s if self.judging.present?
    string += "<h1>Prizes</h1>" + self.prizes.to_s if self.prizes.present?
    string += "<h1>Contact</h1>" + self.contact.to_s if self.contact.present?
    string
  end
  def mob_combined

    string = ""
    string +='<h2 align="center"><b>Team size limit:</b> '+self.team_size.to_s+' people'
    string +='&nbsp&nbsp|&nbsp&nbsp<b>Eligibility:</b> '+self.eligibilty.to_s if self.eligibilty.present?
    string += '&nbsp&nbsp|&nbsp&nbsp<b>Time:</b> '+self.event_date_time.strftime("%D %r") if self.event_date_time.present?
    string += '<br><b>Registration Deadline:</b> '+self.registration_deadline.strftime("%D %r") if self.registration_deadline.present?
    string += '&nbsp&nbsp|&nbsp&nbsp<b>Venue:</b> '+self.venue.to_s if self.venue.present?
    string += '</h2>'
    string += "<h1>Description</h1>" + self.description.to_s if self.description.present?
    string += "<h1>Rules</h1>" + self.rules.to_s if self.rules.present?
    string += "<h1>Judging</h1>" + self.judging.to_s if self.judging.present?
    string += "<h1>Prizes</h1>" + self.prizes.to_s if self.prizes.present?
    string += "<h1>Contact</h1>" + self.contact.to_s if self.contact.present?
    string
  end

  def total_participant_count
    self.participants.count.to_i + self.registrations.count.to_i
  end
  rails_admin do
    show do
      field :name
      field :participant_count do 
        formatted_value do
          bindings[:object].total_participant_count.to_s
        end
      end
      field :categories
      field :description do
        pretty_value do
          bindings[:object].description.html_safe
        end
      end
      field :users
      field :rules do
        pretty_value do
          bindings[:object].rules.html_safe
        end
      end
      field :judging do
        pretty_value do
          bindings[:object].judging.html_safe
        end
      end
      field :event_date_time
      field :team_size
      field :venue
      field :eligibilty
      field :registration_deadline
      field :prizes do
        pretty_value do
          bindings[:object].prizes.html_safe
        end
      end
      field :contact do
        pretty_value do
          bindings[:object].contact.html_safe
        end
      end
      field :photo
      field :registrations
      field :teams
      field :participants
      field :notifications
    end
    list do
      field :name
      field :categories
      field :users
      field :participant_count do 
        formatted_value do
          bindings[:object].total_participant_count.to_s
        end
      end
    end
    edit do
      field :name
      field :categories
      field :team_size
      field :photo
      field :event_date_time
      field :venue
      field :eligibilty
      field :registration_deadline
      field :description, :wysihtml5 do
          config_options toolbar: {
            fa: true,
            image: false,
            link: false
          } # use font-awesome instead of glyphicon, disable images
        end
      field :rules, :wysihtml5 do
          config_options toolbar: {
            fa: true,
            image: false,
            link: false
          } # use font-awesome instead of glyphicon, disable images
        end
      field :judging, :wysihtml5 do
          config_options toolbar: {
            fa: true,
            image: false,
            link: false
          } # use font-awesome instead of glyphicon, disable images
        end
      field :prizes, :wysihtml5 do
          config_options toolbar: {
            fa: true,
            image: false,
            link: false
          } # use font-awesome instead of glyphicon, disable images
        end
      field :contact, :wysihtml5 do
          config_options toolbar: {
            fa: true,
            image: false,
            link: false
          } # use font-awesome instead of glyphicon, disable images
        end
      field :users
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find_by_short_code(params[:id])
      unless @event
        @event = Event.find_by_id(params[:id])      
      end
    end

end

app/views/events/index.html.erb
<section id="event" class="services bg-prime header" style="height: auto">
  <div class="container text-vertical-center">
    <div class="row text-center">
      <div class="col-lg-10 col-lg-offset-1">
        <h2 style="color:white">Esya 2015</h2>
        <hr class="small">
        <div class="row">
          <div class="col-md-4 col-sm-4 col-xs-6 tile">
          <div class="inner-tile">
            <a href="#flagship_event">
              Flagship Events
            </a>
          </div>
          </div>
          <div class="col-md-4 col-sm-4 col-xs-6 tile">
          <div class="inner-tile">
            <a href="#techathlon_event" style="color:white">
              Techathlon Events
            </a>
          </div>
          </div>
          <div class="col-md-4 col-sm-4 col-xs-6 tile">
          <div class="inner-tile">
            <a href="#cse_event">
              CSE Events
            </a>
          </div>
          </div>
          <div class="col-md-4 col-sm-4 col-xs-6 tile">
          <div class="inner-tile">
            <a href="#ece_event">
              ECE Events
            </a>
          </div>
          </div>
          <div class="col-md-4 col-sm-4 col-xs-6 tile">
          <div class="inner-tile">
            <a href="#non_tech_event">
              Non Tech Events
            </a>
          </div>
          </div>
          <div class="col-md-4 col-sm-4 col-xs-6 tile">
          <div class="inner-tile">
            <a href="#school_event" style="color:white">
              School Events
            </a>
          </div>
          </div>
          <div class="col-md-4 col-sm-4 col-xs-6 tile">
          <div class="inner-tile">
            <a href="#workshop_event" style="color:white">
              Workshop Events
            </a>
          </div>
          </div>
          <div class="col-md-4 col-sm-4 col-xs-6 tile">
          <div class="inner-tile">
            <a href="#all_events">
              All Events
            </a>
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


<section id="flagship_event" class="services bg-prime header" style="height: auto">
  <div class="container text-vertical-center">
    <div class="row text-center">
      <div class="col-lg-10 col-lg-offset-1">
        <h2 style="color:white">Flagship Events</h2>
        <hr class="small">
        <div class="row">
          <% Category.where(name: "Flagship").first.events.each do |event| %>
            <div class="col-md-4 col-sm-4 col-xs-6 tile">
            <div class="inner-tile">
              <%= link_to event.to_s ,event_path(event.short_code) %>
            </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="techathlon_event" class="services bg-prime header" style="height: auto">
  <div class="container text-vertical-center">
    <div class="row text-center">
      <div class="col-lg-10 col-lg-offset-1">
        <h2 style="color:white">Techathlon Events</h2>
        <hr class="small">
        <div class="row">
          <% Category.where(name: "Techathlon").first.events.each do |event| %>
            <div class="col-md-4 col-sm-4 col-xs-6 tile">
            <div class="inner-tile">
              <%= link_to event.to_s ,event_path(event.short_code) %>
            </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="cse_event" class="services bg-prime header" style="height: auto">
  <div class="container text-vertical-center">
    <div class="row text-center">
      <div class="col-lg-10 col-lg-offset-1">
        <h2 style="color:white">CSE Events</h2>
        <hr class="small">
        <div class="row">
          <% Category.where(name: "CSE").first.events.each do |event| %>
            <div class="col-md-4 col-sm-4 col-xs-6 tile">
            <div class="inner-tile">
              <%= link_to event.to_s ,event_path(event.short_code) %>
            </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="ece_event" class="services bg-prime header" style="height: auto">
  <div class="container text-vertical-center">
    <div class="row text-center">
      <div class="col-lg-10 col-lg-offset-1">
        <h2 style="color:white">ECE Events</h2>
        <hr class="small">
        <div class="row">
          <% Category.where(name: "ECE").first.events.each do |event| %>
            <div class="col-md-4 col-sm-4 col-xs-6 tile">
            <div class="inner-tile">
              <%= link_to event.to_s ,event_path(event.short_code) %>
            </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="non_tech_event" class="services bg-prime header" style="height: auto">
  <div class="container text-vertical-center">
    <div class="row text-center">
      <div class="col-lg-10 col-lg-offset-1">
        <h2 style="color:white">Non Tech Events</h2>
        <hr class="small">
        <div class="row">
          <% Category.where(name: "Non Tech").first.events.each do |event| %>
            <div class="col-md-4 col-sm-4 col-xs-6 tile">
            <div class="inner-tile">
              <%= link_to event.to_s ,event_path(event.short_code) %>
            </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="school_event" class="services bg-prime header" style="height: auto">
  <div class="container text-vertical-center">
    <div class="row text-center">
      <div class="col-lg-10 col-lg-offset-1">
        <h2 style="color:white">School Events</h2>
        <hr class="small">
        <div class="row">
          <% Category.where(name: "School").first.events.each do |event| %>
            <div class="col-md-4 col-sm-4 col-xs-6 tile">
            <div class="inner-tile">
              <%= link_to event.to_s ,event_path(event.short_code) %>
            </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="workshop_event" class="services bg-prime header" style="height: auto">
  <div class="container text-vertical-center">
    <div class="row text-center">
      <div class="col-lg-10 col-lg-offset-1">
        <h2 style="color:white">Workshops</h2>
        <hr class="small">
        <div class="row">
          <% Category.where(name: "Workshop").first.events.each do |event| %>
            <div class="col-md-4 col-sm-4 col-xs-6 tile">
            <div class="inner-tile">
              <%= link_to event.to_s ,event_path(event.short_code) %>
            </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="all_events" class="services bg-prime header" style="height: auto">
  <div class="container text-vertical-center">
    <div class="row text-center">
      <div class="col-lg-10 col-lg-offset-1">
        <h2 style="color:white">All Events</h2>
        <hr class="small">
        <div class="row">
          <% @events.each do |event| %>
            <div class="col-md-4 col-sm-4 col-xs-6 tile">
            <div class="inner-tile">
              <%= link_to event.to_s ,event_path(event.short_code) %>
            </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/events/show.html.erb
<section id="event" class="services bg-prime header">
  <div class="container-fluid event-image-wrapper">
    <div class="col-lg-10 col-lg-offset-1">
      <%= image_tag @event.photo, class: "event-header-mob" if @event.photo.present?%>
    </div>
  </div>
  <div class="container-fluid">
    <div class="row text-center">
      <div class="col-lg-10 col-lg-offset-1">
        <h2 style="color:white"><%= @event.name.to_s %></h2>
        <%= link_to "Register", register_event_path(short_code: @event.short_code), class: "btn btn-lg btn-light" %>
        <hr class="small">
        <div class="event-text">
          <%= @event.mob_combined.html_safe %>
        </div>
      </div>
    </div>
  </div>
</section>